project:
  type: website
  output-dir: docs    # <- add / change this line
  render: 
    - 1_EvaluationMetrics_tidymodels.qmd
    - Classification_Performance_tidymodels_ROC.qmd
    - DecisionTree_tidymodels_section.qmd
    - random_forest_tidymodels_exercise.qmd
   # - random_forest_sklearn_pima_exercise_v2.qmd

execute:
  echo: true
  python:
    version: "r-reticulate"
    
website:
  back-to-top-navigation: true
  page-navigation: true
  title: "HDS MSc - Module 3 - Overfitting, DT & RF"
  navbar:
    background: primary
    search: true
    left:
      - text: "Overfitting, DT and RF"
        file: 1_EvaluationMetrics_tidymodels.qmd
 
  sidebar:
    - title: "Overfitting, DT and RF"
      contents:
        #- 3_Confusion.qmd
        - 1_EvaluationMetrics_tidymodels.qmd
        - Classification_Performance_tidymodels_ROC.qmd
        - DecisionTree_tidymodels_section.qmd
        - random_forest_tidymodels_exercise.qmd
     #   - random_forest_sklearn_pima_exercise_v2.qmd
  
  page-footer: 
    left: "Copyright 2025, Laura Bravo" 
    background: light
    right: 
      - icon: twitter 
        href: https://twitter.com/laura_bravo94
      - icon: github
        href: https://github.com/LauBra/RIntro2023
    
format:
  html:
    theme: cosmo
  #  css: styles.css
    toc: true
   # code-fold: true
    code-tools: true
    code-link: true

editor: visual

